### ISSUE TITLE
mcabber.state

### ISSUE THREAD

**Issue by spavlovich001** [stef/mcabber#1]
version 10.2(debian stable)
my config:

set jid = some@jabber.org
set password = some_pwd
set default_server = jabber.org
set port = 5222
set resource = real_home
set disable_random_resource = 1
set priority = 3
set priority_away = 0
set ignore_self_presence = 1
set tls = 1
set nickname = some_nick
set pinginterval = 40
set lang = en
set help_dirs = "/usr/share/mcabber/help;~/share/mcabber/help"
set help_to_current = 0
set cmdhistory_lines = 250
set roster_display_filter = ofdna
set roster_no_leading_space = 0
set completion_ignore_case = 1
set logging = 1
set load_logs = 1
set logging_dir = ~/.mcabber/histo/
set logging_ignore_status = 1
set load_muc_logs = 1
set max_history_age = 0
set statefile = /var/tmp/myram/.mcabber/mcabber.state
set max_history_blocks = 8
set iq_version_hide_os = 1
set iq_last_disable = 1
set iq_last_disable_when_notavail = 1
set iq_hide_requests = 1
set modules_dir = /usr/lib/mcabber/
set events_ignore_active_window = 0
set event_log_files = 0
set event_log_dir = ~/.mcabber/event_files
set eventcmd_use_nickname = 1
set fifo_name = /var/tmp/myram/.mcabber/mcabber.fifo
set fifo_hide_commands = 0
set fifo_ignore = 0
module load fifo
set tracelog_level = 1
set tracelog_file = ~/.mcabber/mcabber.log
set autoaway = 600
set muc_print_status = 1
set muc_print_jid = 0
set muc_completion_suffix = ": "
set muc_bookmark_autoupdate = 1
set message_autoaway = Auto-away (idle)
set escdelay = 50
set color_background   = 234
set color_bgstatus     = 235
color muc \* on
set log_win_height = 2
set roster_width=16
set log_win_on_top = 1
set roster_hide_domain = 1
set buddy_format = 3
set time_prefix = 1
set log_display_presence = 0
set show_status_in_buffer = 0
set caps_directory = "~/.mcabber/caps"
alias me = say /me
alias online   = status online
alias away     = status away
alias dnd      = status dnd
alias notavail = status notavail
bind 17 = roster unread_next
bind 24 = roster alternate
bind 269 = roster toggle_offline
bind 276 = roster toggle
bind 521 = buffer up
bind 514 = buffer down
bind 266 = /names
bind 267 = /clear
bind 272 = msay begin

situation: I run mcabber, and have 6 unread msg in 6 conferences. But mcabber.state or not available or available, but if I read first message conference - mcabber.state dissaper

[code]
┌─[user@debian]─[~/.mcabber]
└──╼ ls /var/tmp/myram/.mcabber/
mcabber.fifo  unread

**Comment by stef** [comment]
i'm not sure this is meant for me. this repo is an old fork of mcabber for some of my own patches to it.  you might want to repost this bug on the official bugtracker: https://bitbucket.org/McKael/mcabber-crew/issues/?status=new&status=open
